# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG

ldap:
  url: ldap://172.18.193.115:389
  domain: DC=mmredes,DC=com
  context:
    factory: com.sun.jndi.ldap.LdapCtxFactory
  security:
    authentication: simple
